// src/Utils/books.js
const books = [
  {
    id: 1,
    title: "Belajar JavaScript Dasar",
    author: "Andi Prasetyo",
    year: 2021,
    description: "Panduan lengkap untuk pemula yang ingin belajar JavaScript dari nol.",
    image: "https://imgs.search.brave.com/MGcoQufy6TOwQf2M_BdR-IbRG6sk5kpZp12UBjyXQlU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/cGl4YWJheS5jb20v/cGhvdG8vMjAyMC8w/NC8zMC8xNS8zNC9j/b2RlLTUxMTMzNzRf/NjQwLmpwZw",
  },
  {
    id: 2,
    title: "React untuk Pemula",
    author: "Dina Sari",
    year: 2022,
    description: "Mengenal konsep dan praktik membuat aplikasi React modern.",
    image: "https://imgs.search.brave.com/kPK-FuQbdsL-1MbZAsr_fePG0mW7ey9vVe45EnCbtSs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dW5jbGViaWdiYXku/Y29tL19uZXh0L2lt/YWdlP3VybD1odHRw/czovL2Nkbi5oYXNo/bm9kZS5jb20vcmVz/L2hhc2hub2RlL2lt/YWdlL3VwbG9hZC92/MTYzNjMyNDAyMjA4/Mi96NTlxdnMxWEou/cG5nJnc9Mzg0MCZx/PTc1",
  },
  {
    id: 3,
    title: "Belajar HTML dan CSS",
    author: "Rudi Hartono",
    year: 2020,
    description: "Dasar-dasar HTML dan CSS untuk membangun halaman web.",
    image: "https://imgs.search.brave.com/JsjTIrhkKJ2fVnF9cUNd0e0otkxExO98N3QrcILqnQ4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/bmVzYWJhbWVkaWEu/Y29tL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDE3LzAxL0JlbGFq/YXItSFRNTC1QYXJ0/LTE2LmpwZw",
  },
  {
    id: 4,
    title: "Mastering Node.js",
    author: "Lina Putri",
    year: 2023,
    description: "Panduan lengkap membangun backend dengan Node.js.",
    image: "https://imgs.search.brave.com/DQAbc3exLr8U2iNsQ3b2IfwtHI8y-w_r9bdZDKREDmA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/amFnb2FuaG9zdGlu/Zy5jb20vYmxvZy93/cC1jb250ZW50L3Vw/bG9hZHMvMjAyMi8w/My9Ob2RlLUpzLUNv/dmVyLTM4MHgyMjAu/cG5n",
  },
  {
    id: 5,
    title: "Vue.js Modern",
    author: "Ahmad Fauzi",
    year: 2021,
    description: "Framework progresif untuk membangun antarmuka web.",
    image: "https://example.com/images/vue.jpg",
  },
  {
    id: 6,
    title: "TypeScript in Action",
    author: "Siti Nurhaliza",
    year: 2022,
    description: "Tingkatkan kualitas kode JavaScript dengan TypeScript.",
    image: "https://example.com/images/typescript.jpg",
  },
  {
    id: 7,
    title: "Express.js untuk Pemula",
    author: "Budi Santoso",
    year: 2020,
    description: "Membangun REST API dengan cepat dan efisien.",
    image: "https://example.com/images/express.jpg",
  },
  {
    id: 8,
    title: "MongoDB Handbook",
    author: "Mega Lestari",
    year: 2023,
    description: "Belajar menggunakan database NoSQL MongoDB.",
    image: "https://example.com/images/mongodb.jpg",
  },
  {
    id: 9,
    title: "Next.js & SSR",
    author: "Rama Wijaya",
    year: 2024,
    description: "Optimalkan performa React dengan server-side rendering.",
    image: "https://example.com/images/nextjs.jpg",
  },
];

export default books;
